set-option -g default-shell /usr/bin/zsh
set-option -g default-terminal tmux-256color
set-option -as terminal-features ",xterm-256color:RGB"
set-option -as terminal-features ",xterm-ghostty:RGB"

if-shell "test -r /opt/agent-shell/tmux.conf" \
  "source-file /opt/agent-shell/tmux.conf"
